language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-19.1.0
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - source build/wait_for_emulator.sh
  - adb shell input keyevent 82 &

script:
  - gradle build main:test main:connectedAndroidTest
